@echo off
cd /d "C:\Users\Immanuelle\Documents\Github"

set /p REPO_NAME="Enter repo name: "

if "%REPO_NAME%"=="" (
    echo No name entered. Exiting.
    pause
    exit /b 1
)

if exist "%REPO_NAME%" (
    echo Folder "%REPO_NAME%" already exists. Exiting.
    pause
    exit /b 1
)

mkdir "%REPO_NAME%"
cd /d "C:\Users\Immanuelle\Documents\Github\%REPO_NAME%"
git init

:: Generate CLAUDE.md with current date/time
for /f "tokens=1-3 delims=/" %%a in ('date /t') do set MYDATE=%%c-%%a-%%b
for /f "tokens=1-2 delims= " %%a in ('time /t') do set MYTIME=%%a %%b

(
echo # %REPO_NAME%
echo.
echo IMPORTANT
echo Do not enter planning-only modes. All thinking must produce files and commits.
echo if the scope is not immediately clear make the directory /planning and create many .md files there explaining the planning process instead of using your own planning mode
echo please replace the PLACEHOLDER DESCRIPTION section of readme.md with a proper project summary as soon as the purpose of the repo is known. 
echo ## Project Context
echo This is a new, empty repository created on %MYDATE% at %MYTIME% using the `new-repo.bat` bootstrapping tool.
echo The intent is to use Claude Code to build and populate this project from scratch.
echo.
echo ## Workflow Guidelines
echo - **Commit early and often.** Every meaningful change should be committed with a clear, descriptive summary that explains *why* the change was made, not just what changed.
echo - **Keep this claude.md up to date.** As the project takes shape, update this file with architectural decisions, conventions, dependencies, and anything Claude needs to know to work effectively in this repo. It is not useful to keep the boostrapping project context info in claude.md once a project is up and running.
echo - **Do not enter planning mode, please clearly edit the repo with every single architectural decision and even just thoughts you have. Commit them frequently, because commits can be easily undone**
echo - **Please regularly update the human aimed readme.md to provide more context for a human user**
echo.
echo ## Project Description
echo _TODO: Describe what this project is about._
echo.
echo ## Architecture and Conventions
echo _TODO: Document key decisions, file structure, and patterns as they emerge._
)> claude.md

:: Generate a minimal human-aimed README.md

(
echo(# %REPO_NAME%
echo(
echo(This README was generated by new-repo.bat as %REPO_NAME%.
echo(
echo(---
echo(
echo(## PLACEHOLDER DESCRIPTION
echo(
echo(This repository was created via a command-line bootstrap process and initialized as a Git repository immediately.
echo(This section should be replaced with a concrete project description as soon as the purpose of the repository is known.
echo(
echo(---
echo(
echo(## Initial repository contents
echo(
echo(This repository is intentionally initialized with a small number of files.
echo(Each file has a specific purpose in the early-stage workflow:
echo(
echo(- README.md
echo(  Human-facing documentation. This file should be updated as soon as the project’s purpose and scope are known.
echo(
echo(- CLAUDE.md
echo(  Instructions and constraints for AI-assisted development, including workflow rules and commit expectations.
echo(
echo(- .gitignore
echo(  Intentionally minimal. Exists to reserve the decision space for ignore rules once tooling is known.
echo(
echo(- runClaude.bat
echo(  Convenience script to launch Claude from the repository root with the correct working directory.
echo(
echo(- runCodex.bat
echo(  Convenience script to launch Codex from the repository root with the correct working directory.
echo(
echo(No assumptions are made yet about language, framework, runtime, or tooling.
echo(All such decisions should be introduced explicitly and recorded in Git history.
echo(
echo(---
echo(
echo(## Intended workflow
echo(
echo(This project is intended to be developed by launching an AI assistant via the provided batch scripts
echo(and iteratively editing files and committing changes as decisions are made.
echo(
echo(Planning-only modes should be avoided in favor of durable file edits and frequent commits.
)> README.md

:: Generate !runClaude.bat
(
echo @echo off
echo cd /d "%%~dp0"
echo.
echo echo ==========================================
echo echo Launching Claude from repo root:
echo echo 
echo echo ==========================================
echo echo.
echo claude
)> "!runClaude.bat"

:: Generate minimal .gitignore (intent-only)

(
echo(# This .gitignore is intentionally minimal.
echo(# Flesh this out once the project language,
echo(# tooling, and runtime environment are known.
echo(#
echo(# Claude:
echo(# - Expand this file only after project scope is clear.
echo(# - Avoid speculative or catch-all ignore rules.
echo(# - Data files such as csv files might be essential files to be tracked in this repo
)> .gitignore




git add claude.md
git add !runClaude.bat
git add README.md
git add .gitignore

git commit -m "Initial commit: bootstrap CLAUDE.md"

start "" explorer "C:\Users\Immanuelle\Documents\Github\%REPO_NAME%"
start "" cmd /k "cd /d "C:\Users\Immanuelle\Documents\Github\%REPO_NAME%" && claude"
