"""``cleanvibe chat`` — scaffold a git-tracked, agentic conversation on one topic.

Not a software project: a conversation between the user and Claude that is
research-heavy and light on code, kept in a private git repo so it can be
resumed, searched, and shared. It keeps the cleanvibe basics (``queue.md``,
``devlog.md``, ``data_lake/``, the vendored skills) and adds:

* ``notes/`` for conclusions and sources, and a README that summarizes where
  the conversation stands;
* a queue whose first item is asking the user what they are trying to do; and
* git-tracked session logs: ``.claude/settings.json`` runs
  ``.claude/hooks/save_session_log.py`` on the Stop and SessionEnd hooks, which
  copies the transcript into ``sessions/`` and commits it.

The name is optional: with none, the project is ``chat-YYYY-MM-DD`` in the
current directory, auto-suffixed ``-2``/``-3`` if that already exists.
"""

from __future__ import annotations

import platform
from datetime import datetime
from pathlib import Path

from . import __version__, skills, templates
from .scaffold import _git_init, _launch_claude, _write, _write_gitkeep


def default_chat_path(base: Path | None = None) -> Path:
    """``chat-YYYY-MM-DD`` under ``base`` (cwd), suffixed -2, -3, … if taken."""
    base = Path(".") if base is None else base
    path = base / f"chat-{datetime.now().strftime('%Y-%m-%d')}"
    n = 2
    candidate = path
    while candidate.exists():
        candidate = path.with_name(f"{path.name}-{n}")
        n += 1
    return candidate


def chat_project(
    path: Path,
    topic: str | None = None,
    dry_run: bool = False,
    no_claude: bool = False,
) -> None:
    """Scaffold a chat project and (unless ``no_claude``) launch Claude into it."""
    project_name = path.name
    is_windows = platform.system() == "Windows"

    if dry_run:
        print(f"[dry-run] Chat project: {path}")
        if topic:
            print(f"[dry-run] Topic: {topic}")
        for rel in (
            "CLAUDE.md",
            "README.md",
            "queue.md",
            "devlog.md",
            ".gitignore",
            "notes/.gitkeep",
            "sessions/.gitkeep",
            "data_lake/.gitkeep",
            ".claude/settings.json (session-log hooks)",
            ".claude/hooks/save_session_log.py",
            ".claude/skills/ (6 skills)",
        ):
            print(f"[dry-run] Would write: {path / rel}")
        if is_windows:
            print(f"[dry-run] Would write: {path / '!runClaude.bat'}")
        print(f"[dry-run] Would run: git init")
        print(f"[dry-run] Would run: git add . && git commit")
        if not no_claude:
            print(f"[dry-run] Would launch: claude (with --remote-control)")
        return

    path.mkdir(parents=True, exist_ok=True)
    print(f"Creating chat project: {path}")

    _write(path / "CLAUDE.md", templates.chat_claude_md(project_name, topic))
    _write(path / "README.md", templates.chat_readme_md(project_name, topic))
    _write(path / "queue.md", templates.chat_queue_md(project_name, topic))
    _write(path / "devlog.md", templates.devlog_md(project_name))
    _write(path / ".gitignore", templates.GITIGNORE)

    skills.write_skills(path)

    _write_gitkeep(path / "notes")
    _write_gitkeep(path / "sessions")
    _write_gitkeep(path / "data_lake")

    _write(path / ".claude" / "settings.json", templates.chat_settings_json())
    hooks = path / ".claude" / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    _write(hooks / "save_session_log.py", templates.CHAT_SAVE_SESSION_LOG_PY)

    if is_windows:
        _write(path / "!runClaude.bat", templates.runclaude_bat("chat"))

    message = (
        f"Initial commit: chat scaffolded with cleanvibe v{__version__}\n"
        f"\n"
        f"`cleanvibe chat` — a git-tracked conversation about one topic.\n"
        f"Generated by cleanvibe (https://github.com/EmmaLeonhart/cleanvibe):\n"
        f"- CLAUDE.md (ask-first conversation rules)\n"
        f"- queue.md (first item: ask the user what they are trying to do)\n"
        f"- devlog.md (dated entries — where \"done\" lives)\n"
        f"- notes/ (conclusions + sources), data_lake/ (files to discuss)\n"
        f"- sessions/ + .claude/settings.json + .claude/hooks/save_session_log.py\n"
        f"  (session transcripts saved and committed on every response)"
    )
    _git_init(path, message=message)

    if not no_claude:
        _launch_claude(path, templates.starting_prompt("chat"), remote_control=True)
