"""``cleanvibe original`` — scaffold a standalone *original-research* project
whose **topic is uncertain**.

``cleanvibe original`` is ``cleanvibe research`` for the case where you do NOT
yet have a fixed research question. It keeps everything ``research`` has —
``data_lake/``, ``literature/``, the three-cron playbook, the themed GitHub
Pages report, the ``todo.md`` → ``queue.md`` → ``devlog.md`` loop — and prepends
one distinctive bootstrap step:

* a **topic-finding loop** (committed under ``topics/``): explore the focus area,
  generate and score candidate research questions, and converge on ONE *before*
  the literature review narrows in.

The optional seed is an ``area`` (a field / domain to explore), not a
``question`` — the question is what the loop discovers. It lays down the
cleanvibe conventions, git-inits on ``main``, makes the initial commit, and
launches Claude Code.
"""

from __future__ import annotations

import platform
from pathlib import Path

from . import __version__, skills, templates
from .scaffold import _git_init, _launch_claude, _write, _write_gitkeep


def original_project(
    path: Path,
    area: str | None = None,
    dry_run: bool = False,
    no_claude: bool = False,
) -> None:
    """Scaffold an original-research project with a topic-finding-loop-first
    bootstrap (uncertain topic), a literature review, and a themed report."""
    project_name = path.name
    is_windows = platform.system() == "Windows"

    if dry_run:
        print(f"[dry-run] Original-research project: {path}")
        if area:
            print(f"[dry-run] Focus area: {area}")
        for rel in (
            "CLAUDE.md",
            "README.md",
            "queue.md",
            "devlog.md",
            ".gitignore",
            "data_lake/.gitkeep",
            "topics/.gitkeep",
            "literature/.gitkeep",
            "docs/index.html",
            "docs/.nojekyll",
            ".github/workflows/pages.yml",
            ".claude/skills/ (6 skills)",
        ):
            print(f"[dry-run] Would write: {path / rel}")
        if is_windows:
            print(f"[dry-run] Would write: {path / '!runClaude.bat'}")
        print(f"[dry-run] Would run: git init")
        print(f"[dry-run] Would run: git add . && git commit")
        if not no_claude:
            print(f"[dry-run] Would launch: claude")
        return

    path.mkdir(parents=True, exist_ok=True)
    print(f"Creating original-research project: {path}")

    _write(path / "CLAUDE.md", templates.original_claude_md(project_name, area))
    _write(path / "README.md", templates.original_readme_md(project_name, area))
    _write(path / "queue.md", templates.original_queue_md(project_name, area))
    _write(path / "devlog.md", templates.devlog_md(project_name))
    _write(path / ".gitignore", templates.RESEARCH_GITIGNORE)

    skills.write_skills(path)

    # data_lake/ for datasets; topics/ for the topic-finding loop; literature/
    # for the literature review on the chosen question.
    _write_gitkeep(path / "data_lake")
    _write_gitkeep(path / "topics")
    _write_gitkeep(path / "literature")

    # docs/ is the published GitHub Pages report site (committed, themed).
    docs = path / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    _write(docs / "index.html", templates.original_index_html(project_name, area))
    _write(docs / ".nojekyll", "")

    workflows = path / ".github" / "workflows"
    workflows.mkdir(parents=True, exist_ok=True)
    _write(workflows / "pages.yml", templates.RESEARCH_PAGES_YML)

    if is_windows:
        _write(path / "!runClaude.bat", templates.RUNCLAUDE_BAT)

    message = (
        f"Initial commit: original-research project scaffolded with cleanvibe "
        f"v{__version__}\n"
        f"\n"
        f"`cleanvibe original` — original research with an UNCERTAIN topic "
        f"(research + a topic-finding loop).\n"
        f"Generated by cleanvibe (https://github.com/Immanuelle/cleanvibe):\n"
        f"- CLAUDE.md (workflow: topic finding -> question -> literature review "
        f"-> experiments -> findings)\n"
        f"- queue.md (topic-finding-loop-first bootstrap; three-cron playbook)\n"
        f"- todo.md is written during bootstrap (long-horizon research plan)\n"
        f"- devlog.md (dated entries — where \"done\" lives)\n"
        f"- topics/ (the topic-finding loop: candidates, scoring, selection)\n"
        f"- literature/ (the literature review on the chosen question)\n"
        f"- docs/ (themed GitHub Pages report site + built PDF)\n"
        f"- .github/workflows/pages.yml (publishes docs/, builds the PDF)"
    )
    _git_init(path, message=message)

    if not no_claude:
        _launch_claude(path)
