"""``cleanvibe research`` — scaffold a standalone *original-research* project.

Like ``cleanvibe new`` this creates a fresh project for your OWN work (it is
NOT a replication of someone else's paper). It keeps everything ``new`` has —
``data_lake/``, the three-cron playbook, the ``todo.md`` → ``queue.md`` →
``devlog.md`` loop — and adds two things borrowed from the replication flow:

* an up-front **literature review** step (agentic RAG) before any building,
  with sources + a synthesized survey committed under ``literature/``; and
* a published, **themed GitHub Pages report** under ``docs/`` (warm "paper"
  light theme + dark-mode variant) plus a transportable PDF, built by
  ``.github/workflows/pages.yml``.

It lays down the cleanvibe conventions, git-inits on ``main``, makes the
initial commit, and launches Claude Code.
"""

from __future__ import annotations

import platform
from pathlib import Path

from . import __version__, templates
from .scaffold import _git_init, _launch_claude, _write, _write_gitkeep


def research_project(
    path: Path,
    question: str | None = None,
    dry_run: bool = False,
    no_claude: bool = False,
) -> None:
    """Scaffold an original-research project with a literature-review-first
    bootstrap and a themed GitHub Pages report."""
    project_name = path.name
    is_windows = platform.system() == "Windows"

    if dry_run:
        print(f"[dry-run] Research project: {path}")
        if question:
            print(f"[dry-run] Research question: {question}")
        for rel in (
            "CLAUDE.md",
            "README.md",
            "queue.md",
            "devlog.md",
            ".gitignore",
            "data_lake/.gitkeep",
            "literature/.gitkeep",
            "docs/index.html",
            "docs/.nojekyll",
            ".github/workflows/pages.yml",
        ):
            print(f"[dry-run] Would write: {path / rel}")
        if is_windows:
            print(f"[dry-run] Would write: {path / '!runClaude.bat'}")
        print(f"[dry-run] Would run: git init")
        print(f"[dry-run] Would run: git add . && git commit")
        if not no_claude:
            print(f"[dry-run] Would launch: claude")
        return

    path.mkdir(parents=True, exist_ok=True)
    print(f"Creating research project: {path}")

    _write(path / "CLAUDE.md", templates.research_claude_md(project_name, question))
    _write(path / "README.md", templates.research_readme_md(project_name, question))
    _write(path / "queue.md", templates.research_queue_md(project_name, question))
    _write(path / "devlog.md", templates.devlog_md(project_name))
    _write(path / ".gitignore", templates.RESEARCH_GITIGNORE)

    # data_lake/ for datasets; literature/ for the up-front literature review.
    _write_gitkeep(path / "data_lake")
    _write_gitkeep(path / "literature")

    # docs/ is the published GitHub Pages report site (committed, themed).
    docs = path / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    _write(docs / "index.html", templates.research_index_html(project_name, question))
    _write(docs / ".nojekyll", "")

    workflows = path / ".github" / "workflows"
    workflows.mkdir(parents=True, exist_ok=True)
    _write(workflows / "pages.yml", templates.RESEARCH_PAGES_YML)

    if is_windows:
        _write(path / "!runClaude.bat", templates.RUNCLAUDE_BAT)

    message = (
        f"Initial commit: research project scaffolded with cleanvibe v{__version__}\n"
        f"\n"
        f"`cleanvibe research` — an original-research project (not a "
        f"replication).\n"
        f"Generated by cleanvibe (https://github.com/Immanuelle/cleanvibe):\n"
        f"- CLAUDE.md (research workflow: question -> literature review -> "
        f"experiments -> findings)\n"
        f"- queue.md (literature-review-first bootstrap; three-cron playbook)\n"
        f"- todo.md is written during bootstrap (long-horizon research plan)\n"
        f"- devlog.md (dated entries — where \"done\" lives)\n"
        f"- literature/ (the up-front literature review)\n"
        f"- docs/ (themed GitHub Pages report site + built PDF)\n"
        f"- .github/workflows/pages.yml (publishes docs/, builds the PDF)"
    )
    _git_init(path, message=message)

    if not no_claude:
        _launch_claude(path)
